runtime: custom

env: flex

env_variables:
  PROJECT_ID: 'miso-4cloud'
  GOOGLE_APPLICATION_CREDENTIALS: 'key.json'

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3