#SQLALCHEMY_DATABASE_URI = 'postgresql://cloud:cloud@localhost:5432/cloud' # Cadena de conexión a la base de datos
SQLALCHEMY_DATABASE_URI = 'postgresql://cloud:cloud@10.27.160.3:5432/cloud' # Cadena de conexión a la base de datos
#RUTA_REPOSITORIO = "c:/Temp/"
RUTA_REPOSITORIO = "/temp/"
EXTENSIONES_PERMITIDAS = ["mp3","wav", "ogg"]
EMAIL_SERVER = "datadoc.com.co"
EMAIL_SERVER_PORT = 587
EMAIL_USER = "demo@datadoc.com.co"
EMAIL_PASSWORD = "C5go2$v0"
GCP_PROJECT_NAME = "MISO-4Cloud"
GCP_BUBKET_NAME = "miso4cloud"
MESSAGE_QUEUE_URI="amqp://cloud:cloud@34.125.126.102//"
PUBLISHER_PATH="projects/miso-4cloud/topics/convert"
SUB_PATH="projects/miso-4cloud/subscriptions/convert-sub"
AUTH_PUB_SUB="miso-4cloud-769393b6b084.json"
