version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Cloud
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "90:80"
    depends_on:
      - postgres
  app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - upload_files:/cloud/uploads/uploaded
      - process_files:/cloud/process/process
    depends_on:
      - postgres
volumes:
  upload_files:
  process_files:

